name: Run Bedrock Script

on:
  workflow_dispatch:   # run manually from GitHub UI
  push:
    branches:
      - main

jobs:
  run-bedrock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SERVICE_UAT }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SERVICE_UAT }}
          aws-region: us-west-2

      - name: Run Bedrock script
        run: python bedrock.py
