# Copy umm v from ops to uat
name: Umm V Auto Sync
# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *'  # Set the cron schedule for nightly build (UTC time)
      branches:
        - main
  workflow_dispatch:
    branches:
      - feature/first_implementation

jobs:
  # First job in the workflow installs and verifies the software
  build:
    name: Build, Test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      #########################################################################
      # Environment Setup
      #########################################################################
      # NOTE: This step is platform-specific
      # Checks out this repository and sets up the build/test environment with 
      # gradle
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.3.2

      #########################################################################
      # Install & Pylint & Flake
      #########################################################################
      # NOTE: This step is platform-specific
      # These are gradle-specific steps for installing the application
      - name: Poetry Steps
      - name: Install Software
        working-directory: umm_v_auto
        run: |
          poetry install
          poetry run pylint podaac
          poetry run flake8 podaac

      #########################################################################
      # UMM V Auto Sync
      #########################################################################
      - name: UMM V Auto Sync
        working-directory: umm_v_auto
        env:
          UAT_TOKEN_TEMP: ${{ secrets.LAUNCHPAD_TOKEN_UAT }}
          OPS_TOKEN_TEMP: ${{ secrets.LAUNCHPAD_TOKEN_OPS }}
        run: |
          poetry run python podaac/umm_v_auto_sync.py -ut $UAT_TOKEN_TEMP -ot $OPS_TOKEN_TEMP
