
name: Repo Status Updater
# Controls when the workflow will run
on:
  schedule:
    - cron: '0 9 * * *'  # Set the cron schedule for 1 am PST
  workflow_dispatch:

jobs:
  build:
    name: Refresh Repos Statuses
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      #########################################################################
      # Environment Setup
      #########################################################################
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.5.1

      #########################################################################
      # Install & Run Pylint & Flake
      #########################################################################
      - name: Poetry Steps
        run: |
          poetry install
    #      poetry run pylint ./*
    #      poetry run flake8 .

      #########################################################################
      # Setup Token for GSpread
      #########################################################################
      - name: Setup Token
        env:
          GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
        run: |
          mkdir -p ~/.config/gspread
          echo "$GOOGLE_TOKEN" > ~/.config/gspread/service_account.json

      #########################################################################
      # Start the Repo Status Updater
      #########################################################################
      - name: Generate Repos
        env:
          UAT_TOKEN_TEMP: ${{ secrets.LAUNCHPAD_TOKEN_UAT }}
          OPS_TOKEN_TEMP: ${{ secrets.LAUNCHPAD_TOKEN_OPS }}
          GITHUB_TOKEN_TEMP: ${{ secrets.GH_READ_TOKEN }}
          GITHUB_JPL_TOKEN_TEMP: "No_Token"

          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_SERVICES_OPS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SERVICES_OPS }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_SERVICES_OPS }}
          AWS_DEFAULT_REGION: us-west-2
        run: |
          poetry run python start_data_updater.py -ut $UAT_TOKEN_TEMP -ot $OPS_TOKEN_TEMP -gt $GITHUB_TOKEN_TEMP -jt $GITHUB_JPL_TOKEN_TEMP
