name: Monitor Trek NASA Endpoint

on:
  schedule:
    - cron: "0 * * * *"   # runs every hour on the hour
  workflow_dispatch:          # allow manual trigger

jobs:
  check-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Check NASA endpoint
        id: check
        run: |
          URL="https://trek.nasa.gov/moon/arcgis/rest/services/earth/bluemarble2nd/MapServer?f=json"
          RESPONSE=$(curl -s -w "%{http_code}" -o response.json "$URL")

          echo "HTTP_STATUS=$RESPONSE" >> $GITHUB_ENV

          if [ "$RESPONSE" -ne 200 ]; then
            echo "NASA endpoint returned status $RESPONSE"
            exit 1
          fi

          # Validate JSON
          if ! jq empty response.json > /dev/null 2>&1; then
            echo "NASA endpoint did not return valid JSON"
            exit 1
          fi

  notify-slack:
    needs: check-endpoint
    if: failure()   # <-- only runs if check-endpoint fails
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Test Message
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        run: |
          curl -s -S \
            -X POST \
            -H "Content-Type: application/json" \
            --data-binary @- \
            "https://jpl.slack.com/services/hooks/jenkins-ci?token=${SLACK_API_TOKEN}" <<EOF
          {
            "text": ":rotating_light: NASA Trek url is down so HITIDE UI could be down!\nRepo: $GITHUB_REPOSITORY\nRun: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          }
          EOF

